routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * @param \Illuminate\Routing\Router $router
 */
$optionalLanguageRoutes = function (\Illuminate\Routing\Router $router ) {
    Auth::routes();

    Route::get( '/', 'IndexController@index' )->name( 'home' );

    // users
    Route::group([
        'prefix' => 'user',
        'as'     => 'user.',
    ], function (){
        Route::get( '/', 'UserController@index' )->name( 'index' );

        Route::get( '{user}',
            [ 'as' => 'show', 'uses' => 'UserController@show' ] );

        Route::get( '{id}/edit',
            [ 'as' => 'edit', 'uses' => 'UserController@edit' ] );

        Route::match(['put', 'patch'], '{id}',
            [ 'as' => 'update', 'uses' => 'UserController@update' ] );
    });

    // posts
    Route::group( [
        'prefix' => 'post',
        'as'     => 'post.',
    ],
        function () {
            Route::get( '/', 'PostController@index' )->name( 'index' );
            Route::get( '/{post}', 'PostController@show' )
                 ->name( 'show' );

            Route::group( [
                'middleware' => 'auth',
            ],
                function () {
                    Route::get( '/create', 'PostController@create' )
                         ->name( 'create' );
                    Route::post( '/', 'PostController@store' )
                         ->name( 'store' );
                    Route::get( '/{id}/edit', 'PostController@edit' )
                         ->name( 'edit' );
                    Route::put( '/{id}', 'PostController@update' )
                         ->name( 'update' );
                    Route::delete( '/{id}', 'PostController@destroy' )
                         ->name( 'destroy' );
                } );
        } );

    //Route::resource('post', 'PostController');
    //Route::resource('post', 'PostController')->only(['index']);
    //Route::resource('post', 'PostController')->except(['create', 'update', 'destroy']);

    Route::group( [
        'middleware' => 'auth',
        'prefix'     => 'admin',
        'namespace'  => 'Admin',
        'as'         => 'admin.',
    ],
        function () {
            Route::get( '/', 'IndexController@all' )->name( 'home' );
            Route::resource( 'users', 'UserController' );
            Route::resource( 'posts', 'PostController' );
        } );
};

Route::group( [ 'middleware' => 'locale' ], $optionalLanguageRoutes );
Route::group( [
    'prefix'     => '{locale?}',
    'middleware' => 'locale',
    'where'      => [ 'locale' => 'en|ru' ],
],
    $optionalLanguageRoutes );

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'first_name', 'last_name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getRouteKeyName()
    {
        return 'id';
    }

    public function posts(){
        return $this->hasMany(Post::class, 'user_id', 'id');
    }

    // accessors
    public function setPasswordAttribute($password)
    {
        if ($password) {
            $this->attributes['password'] = bcrypt($password);
        }
    }

    public function setFirstNameAttribute($firstName)
    {
        if ($firstName) {
            $this->attributes['first_name'] = ucfirst($firstName);
        }
    }

    public function setLastNameAttribute($lastName)
    {
        if ($lastName) {
            $this->attributes['last_name'] = ucfirst($lastName);
        }
    }

    // getters
    public function getFullNameAttribute()
    {
        return sprintf('%s %s', $this->first_name, $this->last_name);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    public function all()
    {

    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    public function index() {
        $users = User::all();

        return view('pages.user.index', compact('users'));
    }

    public function show($locale, User $user)
    {
        return view('pages.user.show', compact('user'));
    }

    public function edit($locale){
        $user = Auth::user();

        return view('pages.user.edit', compact('user'));
    }
}

resources/views/pages/user/edit.blade.php
@extends('layouts.main')

@section('title', ' | News')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h1>{{ __('Edit User') }} {{ $user->id }}</h1>
                @if($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form action="{{ route('user.update', [app()->getLocale(), $user->id]) }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="post-name">{{ __('Name') }}</label>
                        <input type="text" class="form-control" name="name" id="post-name" value="{{old('name')}}" placeholder="{{ __('Enter name ...') }}">
                    </div>
                    <div class="form-group">
                        <label for="post-first-name">{{ __('First Name') }}</label>
                        <input type="text" class="form-control" name="first-name" id="post-first-name" value="{{old('first-name')}}" placeholder="{{ __('Enter first name ...') }}">
                    </div>
                    <div class="form-group">
                        <label for="post-last-name">{{ __('Last Name') }}</label>
                        <input type="text" class="form-control" name="last-name" id="post-name" value="{{old('last-name')}}" placeholder="{{ __('Enter last name ...') }}">
                    </div>

                    <input class="btn btn-primary" type="submit" value="{{ __('Update') }}" name="user-update">

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/user/index.blade.php
@extends('layouts.main')

@section('title', ' | Users')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h1>{{ __('Users') }}</h1>

                <div class="users-section">

                    @if(!$users->isEmpty())
                        @foreach ($users as $user)
                            <div class="card">
                                <div class="card-header">
                                    <span class="font-weight-bold">
                                        {{$user->full_name}}
                                    </span>
                                </div>
                                <div class="card-body">
                                    <table class="table table-bordered table-hover">
                                        <thead class="thead-dark">
                                        <tr>
                                            <th scope="col">ID</th>
                                            <th scope="col">Full Name</th>
                                            <th scope="col" class="text-center">Posts</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td>{{ $user->id }}</td>
                                            <td>
                                                <a href="{{ route('user.show', [$app->getLocale(), $user->id]) }}">{{ $user->full_name }}</a>
                                            </td>
                                            <td class="text-center">{{count($user->posts)}}</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        @endforeach
                    @else
                        <div class="alert alert-info">
                            <p>{{ __('No users found.') }}</p>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

    @component('components.test-component')
        <div class="alert alert-primary my-2">
            <h3 class="m-0">Hi there, from test component</h3>
        </div>
    @endcomponent

@endsection

resources/views/pages/user/show.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Full Name</th>
                            <th scope="col">E-Mail</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>{{ $user->id }}</td>
                            <td>{{ $user->full_name }}</td>
                            <td><a href="mailto:{{ $user->email }}">{{ $user->email }}</a></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection