routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * @param \Illuminate\Routing\Router $router
 */
$optionalLanguageRoutes = function (\Illuminate\Routing\Router $router ) {
    Auth::routes();

    Route::get( '/', 'IndexController@index' )->name( 'home' );

    // users
    Route::group([
        'prefix' => 'user',
        'as'     => 'user.',
    ], function (){
        Route::get( '/', 'UserController@index' )->name( 'index' );

        Route::get( '{user}',
            [ 'as' => 'show', 'uses' => 'UserController@show' ] );

        Route::get( '{id}/edit',
            [ 'as' => 'edit', 'uses' => 'UserController@edit' ] );

        Route::match(['put', 'patch'], '{id}',
            [ 'as' => 'update', 'uses' => 'UserController@update' ] );
    });

    // posts
    Route::group( [
        'prefix' => 'post',
        'as'     => 'post.',
    ],
        function () {
            Route::get( '/', 'PostController@index' )->name( 'index' );
            Route::get( '/{post}', 'PostController@show' )
                 ->name( 'show' );

            Route::group( [
                'middleware' => 'auth',
            ],
                function () {
                    Route::get( '/create', 'PostController@create' )
                         ->name( 'create' );
                    Route::post( '/', 'PostController@store' )
                         ->name( 'store' );
                    Route::get( '/{id}/edit', 'PostController@edit' )
                         ->name( 'edit' );
                    Route::put( '/{id}', 'PostController@update' )
                         ->name( 'update' );
                    Route::delete( '/{id}', 'PostController@destroy' )
                         ->name( 'destroy' );
                } );
        } );

    //Route::resource('post', 'PostController');
    //Route::resource('post', 'PostController')->only(['index']);
    //Route::resource('post', 'PostController')->except(['create', 'update', 'destroy']);

    Route::group( [
        'middleware' => 'auth',
        'prefix'     => 'admin',
        'namespace'  => 'Admin',
        'as'         => 'admin.',
    ],
        function () {
            Route::get( '/', 'IndexController@all' )->name( 'home' );
            Route::resource( 'users', 'UserController' );
            Route::resource( 'posts', 'PostController' );
        } );
};

Route::group( [ 'middleware' => 'locale' ], $optionalLanguageRoutes );
Route::group( [
    'prefix'     => '{locale?}',
    'middleware' => 'locale',
    'where'      => [ 'locale' => 'en|ru' ],
],
    $optionalLanguageRoutes );

resources/views/partials/fonts.blade.php
<!-- Fonts -->
<link rel="dns-prefetch" href="//fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
@stack('fonts')

resources/views/partials/footer.blade.php
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            Copyright &copy; {{ date('Y') }}
        </div>
    </div>
</div>

resources/views/partials/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>{{ config('app.name', 'Laravel') }}@yield('title')</title>

resources/views/partials/header.blade.php
@include('partials.main-nav')

resources/views/partials/left-sidebar.blade.php
<section>
    <h1 class="title">Section 3</h1>
    <p>
        Section 3 text
    </p>
</section>

<section>
    <h1 class="title">Section 4</h1>
    <p>
        Section 4 text
    </p>
</section>

resources/views/partials/main-nav.blade.php
<nav class="navbar navbar-expand-md navbar-light navbar-laravel">
    <a class="navbar-brand" href="{{ url('/') }}">
        {{ config('app.name', 'Laravel') }}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNavBar" aria-controls="mainNavBar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mainNavBar">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('home', [app()->getLocale()]) }}">Main</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('user.index', [app()->getLocale()]) }}">Users</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('post.index', [app()->getLocale()]) }}">News</a>
            </li>
            <!-- Authentication Links -->
            @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login', [app()->getLocale()]) }}">{{ __('Login') }}</a>
                </li>
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register', [app()->getLocale()]) }}">{{ __('Register') }}</a>
                    </li>
                @endif
            @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                        <a class="dropdown-item" href="{{ route('user.edit', [app()->getLocale(), auth()->user()->id]) }}">{{ __('Edit') }}</a>

                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </div>
</nav>

resources/views/partials/right-sidebar.blade.php
<section>
    <h1 class="title">Section 1</h1>
    <p>
        Section 1 text
    </p>
</section>

<section>
    <h1 class="title">Section 2</h1>
    <p>
        Section 2 text
    </p>
</section>

resources/views/partials/scripts.blade.php
<script src="{{ mix('js/app.js') }}" defer></script>
@stack('scripts')

resources/views/partials/styles.blade.php
<!-- Styles -->
<link href="{{ mix('css/app.css') }}" rel="stylesheet">
@stack('styles')