routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * @param \Illuminate\Routing\Router $router
 */
$optionalLanguageRoutes = function (\Illuminate\Routing\Router $router ) {
    Auth::routes();

    Route::get( '/', 'IndexController@index' )->name( 'home' );

    // users
    Route::group([
        'prefix' => 'user',
        'as'     => 'user.',
    ], function (){
        Route::get( '/', 'UserController@index' )->name( 'index' );

        Route::get( '{user}',
            [ 'as' => 'show', 'uses' => 'UserController@show' ] );

        Route::get( '{id}/edit',
            [ 'as' => 'edit', 'uses' => 'UserController@edit' ] );

        Route::match(['put', 'patch'], '{id}',
            [ 'as' => 'update', 'uses' => 'UserController@update' ] );
    });

    // posts
    Route::group( [
        'prefix' => 'post',
        'as'     => 'post.',
    ],
        function () {
            Route::get( '/', 'PostController@index' )->name( 'index' );
            Route::get( '/{post}', 'PostController@show' )
                 ->name( 'show' );

            Route::group( [
                'middleware' => 'auth',
            ],
                function () {
                    Route::get( '/create', 'PostController@create' )
                         ->name( 'create' );
                    Route::post( '/', 'PostController@store' )
                         ->name( 'store' );
                    Route::get( '/{id}/edit', 'PostController@edit' )
                         ->name( 'edit' );
                    Route::put( '/{id}', 'PostController@update' )
                         ->name( 'update' );
                    Route::delete( '/{id}', 'PostController@destroy' )
                         ->name( 'destroy' );
                } );
        } );

    //Route::resource('post', 'PostController');
    //Route::resource('post', 'PostController')->only(['index']);
    //Route::resource('post', 'PostController')->except(['create', 'update', 'destroy']);

    Route::group( [
        'middleware' => 'auth',
        'prefix'     => 'admin',
        'namespace'  => 'Admin',
        'as'         => 'admin.',
    ],
        function () {
            Route::get( '/', 'IndexController@all' )->name( 'home' );
            Route::resource( 'users', 'UserController' );
            Route::resource( 'posts', 'PostController' );
        } );
};

Route::group( [ 'middleware' => 'locale' ], $optionalLanguageRoutes );
Route::group( [
    'prefix'     => '{locale?}',
    'middleware' => 'locale',
    'where'      => [ 'locale' => 'en|ru' ],
],
    $optionalLanguageRoutes );

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = 'posts';
    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'description', 'user_id'];

    public function author(){
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function setUserIdAttribute($value)
    {
        $this->attributes['user_id'] = 1;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'first_name', 'last_name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getRouteKeyName()
    {
        return 'id';
    }

    public function posts(){
        return $this->hasMany(Post::class, 'user_id', 'id');
    }

    // accessors
    public function setPasswordAttribute($password)
    {
        if ($password) {
            $this->attributes['password'] = bcrypt($password);
        }
    }

    public function setFirstNameAttribute($firstName)
    {
        if ($firstName) {
            $this->attributes['first_name'] = ucfirst($firstName);
        }
    }

    public function setLastNameAttribute($lastName)
    {
        if ($lastName) {
            $this->attributes['last_name'] = ucfirst($lastName);
        }
    }

    // getters
    public function getFullNameAttribute()
    {
        return sprintf('%s %s', $this->first_name, $this->last_name);
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Requests\PostRequest;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();

        return view('pages.post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\PostRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        Post::create(array_merge($request->all(), ['user_id' => 1]));

        return redirect()->route('post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  string  $locale
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($locale, Post $post)
    {
        return view('pages.post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  string  $locale
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($locale, $id)
    {
        $post = Post::find($id);

        return view('pages.post.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  string  $locale
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $locale, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  string  $locale
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($locale, $id)
    {
        //
    }
}

resources/views/pages/post/create.blade.php
@extends('layouts.main')

@section('title', ' | News')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h1>{{ __('Create Post') }}</h1>
                @if($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form action="{{ route('post.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="post-title">{{ __('Title') }}</label>
                        <input type="text" class="form-control" name="title" id="post-title" value="{{old('title')}}" placeholder="{{ __('Enter title ...') }}">
                    </div>
                    <div class="form-group">
                        <label for="post-description">{{ __('Description') }}</label>
                        <textarea class="form-control" id="post-description" name="description" id="" cols="30" rows="10" placeholder="{{ __('Enter description ...') }}">{{old('description')}}</textarea>
                    </div>

                    <input class="btn btn-primary" type="submit" value="{{ __('Create') }}" name="post-save">

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/post/index.blade.php
@extends('layouts.main')

@section('title', ' | News')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h1>News</h1>

                <div class="news-section">
                    @forelse($posts As $post)
                        <div class="card my-3">
                            <div class="card-header">
                                <span class="font-weight-bold">{{$post->title}}</span>
                            </div>
                            <div class="card-body">
                                {{$post->description}}
                            </div>
                            <div class="card-footer">
                                <a class="float-left" href={{ route('user.show', [$app->getLocale(), $post->id]) }}">{{ $post->author->full_name }}</a>
                                <a class="btn btn-primary float-right" href="{{ route('post.show', [app()->getLocale(), $post->id]) }}">{{ __('Read') }}</a>
                            </div>
                        </div>
                    @empty
                        <div class="alert alert-info">
                            <p>Sorry, but there is no news else.</p>
                        </div>
                    @endforelse
                </div>
                @auth
                    <div class="clearfix py-5">
                        <a class="btn btn-danger float-right" href="{{ route('post.create', [app()->getLocale()]) }}">Add new post</a>
                    </div>
                @else
                    <div class="alert alert-info">
                        {{__('Authorised to create new post')}}
                    </div>
                @endauth
            </div>
        </div>
    </div>





@endsection

resources/views/pages/post/show.blade.php
@extends('layouts.main')

@section('title', ' | Detail Post')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h1>@lang('post.title.single')</h1>
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead class="thead-dark">

                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Author</th>
                            <th>Created</th>
                            <th>Updated</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>{{ $post->id }}</td>
                            <td>{{ $post->title }}</td>
                            <td><a href={{ route('user.show', [$app->getLocale(), $post->id]) }}">{{ $post->author->full_name }}</a></td>
                            <td>{{ $post->created_at }}</td>
                            <td>{{ $post->updated_at }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection